### PR TITLE
Small clean-up

### PR DESCRIPTION
**Pull request by pschambacher**
:octopus::computer:

/cc @osheroff @grosser @bquorning 

### Description
From what I've seen, `exec_stmt` was only defined in Rails 2.x
IMHO `disconnect!` should clear all caches so `@_cached_connection_object_id` should be cleared as well.
Renamed `name` into `owner` for `establish_connection` since it's how the method is defined in rails original method, making the code closer to what it is in Rails master.

### Steps to merge
* [ ] :+1: from the team

### Risks
* Low: Statements getting executed in the wrong database due to `exec_stmt` still being defined after all.

### CODE REVIEW

**Comment by grosser** [comment]
:+1: :heart: nice cleanup!

**Comment by osheroff** [comment]
yokay.

**Comment by osheroff** [comment]
:+1:

**Comment by bquorning** [comment]
:+1:

**Pull request merged**
